const data = [
  {
    Id: 785644,
    firstName: "Virat",
    Lastname: "Kohli",
    teamName: "RCB",
    player_type: "Batsman",
    total_match: "432",
    total_run: "10400",
    total_wickets: "15",
    total_centuries: "34",
    upcomingMatchesList: {
      next_match_date: "05/08/2021 07:53:13 AM",
      against_team: "CSK",
    },
  },
  {
    Id: 319946,
    firstName: "Mahendra Singh",
    Lastname: "Dhoni",
    teamName: "CSK",
    player_type: "Batsman",
    total_match: "489",
    total_run: "8990",
    total_wickets: "12",
    total_centuries: "17",
    upcomingMatchesList: {
      next_match_date: "06/10/2021 06:55:27 AM",
      against_team: "DD",
    },
  },
  {
    Id: 346524,
    firstName: "Sachin",
    Lastname: "Tendulkar",
    teamName: "MI",
    player_type: "Batsman",
    total_match: "340",
    total_run: "13000",
    total_wickets: "4",
    total_centuries: "48",
    upcomingMatchesList: {
      next_match_date: "03/07/2021 09:36:34 PM",
      against_team: "RCB",
    },
  },
  {
    Id: 234223,
    firstName: "Ravindra",
    Lastname: "Ashwin",
    teamName: "KXIP",
    player_type: "Bowler",
    total_match: "229",
    total_run: "3000",
    total_wickets: "509",
    total_centuries: "2",
    upcomingMatchesList: {
      next_match_date: "06/28/2021 08:15:21 PM",
      against_team: "CSK",
    },
  },
  {
    Id: 341234,
    firstName: "Ishant",
    Lastname: "Sharma",
    teamName: "RR",
    player_type: "Bowler",
    total_match: "120",
    total_run: "1001",
    total_wickets: "203",
    total_centuries: "-",
    upcomingMatchesList: {
      next_match_date: "05/17/2021 08:52:51 AM",
      against_team: "RR",
    },
  },
  {
    Id: 76463,
    firstName: "Jasprit",
    Lastname: "Bumrah",
    teamName: "CSK",
    player_type: "Bowler",
    total_match: "228",
    total_run: "898",
    total_wickets: "211",
    total_centuries: "-",
    upcomingMatchesList: {
      next_match_date: "03/14/2021 09:13:48 PM",
      against_team: "MI",
    },
  },
  {
    Id: 875871,
    firstName: "KL",
    Lastname: "Rahul",
    teamName: "MI",
    player_type: "Batsman",
    total_match: "229",
    total_run: "8786",
    total_wickets: "44",
    total_centuries: "33",
    upcomingMatchesList: {
      next_match_date: "03/01/2021 10:17:39 PM",
      against_team: "RR",
    },
  },
  {
    Id: 692572,
    firstName: "Rohit",
    Lastname: "Sharma",
    teamName: "MI",
    player_type: "Batsman",
    total_match: "332",
    total_run: "1239",
    total_wickets: "43",
    total_centuries: "45",
    upcomingMatchesList: {
      next_match_date: "04/24/2021 03:54:09 PM",
      against_team: "CSK",
    },
  },
  {
    id: 765744,
    firstName: "Mohammed",
    Lastname: "Shami",
    teamName: "MI",
    player_type: "Bowler",
    total_match: "229",
    total_run: "2822",
    total_wickets: "445",
    total_centuries: "-",
    upcomingMatchesList: {
      next_match_date: "05/16/2021 02:09:53 PM",
      against_team: "RCB",
    },
  },
];

export default data
